default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gilgamesz_development

test:
  <<: *default

production:
  <<: *default
  database: gilgamesz_production
  username: gilgamesz
  password: <%= ENV['GILGAMESZ_DATABASE_PASSWORD'] %>
